### ISSUE TITLE
WARN: Dropping unreachable code [-:15625,13]

### ISSUE THREAD

**Issue by dmitriz** [mattdesl/browserify-example#1]
``` sh
npm run build

> browserify-example@1.0.0 build /Users/z/Repos/browserify-example
> browserify index.js | uglifyjs -cm > bundle.js

WARN: Dropping unreachable code [-:15625,13]
```

**Comment by mattdesl** [comment]
Yeah this is just uglifyjs output on compress. I will see if there is a way to silent it.

**Comment by mattdesl** [comment]
fixed now in latest, using a flag. 

This is a problem with UglifyJS2 in my opinion. See here:
https://github.com/mishoo/UglifyJS2/issues/440

**Comment by dmitriz** [comment]
Hidden now, many thanks!

**Comment by dmitriz** [comment]
BTW, thanks for this no BS alternative to Webpack!
